package pdcurses;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\curses.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("pdcurses") 
public class MEVENT extends StructObject {
	public MEVENT() {
		super();
	}
	/// x, y same as MOUSE_STATUS; z unused
	@Field(0) 
	public int x() {
		return this.io.getIntField(this, 0);
	}
	/// x, y same as MOUSE_STATUS; z unused
	@Field(0) 
	public MEVENT x(int x) {
		this.io.setIntField(this, 0, x);
		return this;
	}
	/// x, y same as MOUSE_STATUS; z unused
	@Field(1) 
	public int y() {
		return this.io.getIntField(this, 1);
	}
	/// x, y same as MOUSE_STATUS; z unused
	@Field(1) 
	public MEVENT y(int y) {
		this.io.setIntField(this, 1, y);
		return this;
	}
	/// x, y same as MOUSE_STATUS; z unused
	@Field(2) 
	public int z() {
		return this.io.getIntField(this, 2);
	}
	/// x, y same as MOUSE_STATUS; z unused
	@Field(2) 
	public MEVENT z(int z) {
		this.io.setIntField(this, 2, z);
		return this;
	}
	/**
	 * equivalent to changes + button[], but<br>
	 * in the same format as used for mousemask()<br>
	 * C type : mmask_t
	 */
	@CLong 
	@Field(3) 
	public long bstate() {
		return this.io.getCLongField(this, 3);
	}
	/**
	 * equivalent to changes + button[], but<br>
	 * in the same format as used for mousemask()<br>
	 * C type : mmask_t
	 */
	@CLong 
	@Field(3) 
	public MEVENT bstate(long bstate) {
		this.io.setCLongField(this, 3, bstate);
		return this;
	}
	public MEVENT(Pointer pointer) {
		super(pointer);
	}
}
