package pdcurses;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\curses.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("pdcurses") 
public class MOUSE_STATUS extends StructObject {
	public MOUSE_STATUS() {
		super();
	}
	/// absolute column, 0 based, measured in characters
	@Field(0) 
	public int x() {
		return this.io.getIntField(this, 0);
	}
	/// absolute column, 0 based, measured in characters
	@Field(0) 
	public MOUSE_STATUS x(int x) {
		this.io.setIntField(this, 0, x);
		return this;
	}
	/// absolute row, 0 based, measured in characters
	@Field(1) 
	public int y() {
		return this.io.getIntField(this, 1);
	}
	/// absolute row, 0 based, measured in characters
	@Field(1) 
	public MOUSE_STATUS y(int y) {
		this.io.setIntField(this, 1, y);
		return this;
	}
	/**
	 * state of each button<br>
	 * C type : short[3]
	 */
	@Array({3}) 
	@Field(2) 
	public Pointer<Short > button() {
		return this.io.getPointerField(this, 2);
	}
	/// flags indicating what has changed with the mouse
	@Field(3) 
	public int changes() {
		return this.io.getIntField(this, 3);
	}
	/// flags indicating what has changed with the mouse
	@Field(3) 
	public MOUSE_STATUS changes(int changes) {
		this.io.setIntField(this, 3, changes);
		return this;
	}
	public MOUSE_STATUS(Pointer pointer) {
		super(pointer);
	}
}
