package pdcurses;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\curses.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("pdcurses") 
public class PDC_VERSION extends StructObject {
	public PDC_VERSION() {
		super();
	}
	/// flags OR'd together (see below)
	@Field(0) 
	public short flags() {
		return this.io.getShortField(this, 0);
	}
	/// flags OR'd together (see below)
	@Field(0) 
	public PDC_VERSION flags(short flags) {
		this.io.setShortField(this, 0, flags);
		return this;
	}
	/// PDC_BUILD at compile time
	@Field(1) 
	public short build() {
		return this.io.getShortField(this, 1);
	}
	/// PDC_BUILD at compile time
	@Field(1) 
	public PDC_VERSION build(short build) {
		this.io.setShortField(this, 1, build);
		return this;
	}
	/// PDC_VER_MAJOR
	@Field(2) 
	public byte major() {
		return this.io.getByteField(this, 2);
	}
	/// PDC_VER_MAJOR
	@Field(2) 
	public PDC_VERSION major(byte major) {
		this.io.setByteField(this, 2, major);
		return this;
	}
	/// PDC_VER_MINOR
	@Field(3) 
	public byte minor() {
		return this.io.getByteField(this, 3);
	}
	/// PDC_VER_MINOR
	@Field(3) 
	public PDC_VERSION minor(byte minor) {
		this.io.setByteField(this, 3, minor);
		return this;
	}
	/// sizeof chtype
	@Field(4) 
	public byte csize() {
		return this.io.getByteField(this, 4);
	}
	/// sizeof chtype
	@Field(4) 
	public PDC_VERSION csize(byte csize) {
		this.io.setByteField(this, 4, csize);
		return this;
	}
	/// sizeof bool
	@Field(5) 
	public byte bsize() {
		return this.io.getByteField(this, 5);
	}
	/// sizeof bool
	@Field(5) 
	public PDC_VERSION bsize(byte bsize) {
		this.io.setByteField(this, 5, bsize);
		return this;
	}
	public PDC_VERSION(Pointer pointer) {
		super(pointer);
	}
}
