package pdcurses;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\curses.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("pdcurses") 
public class WINDOW extends StructObject {
	public WINDOW() {
		super();
	}
	/// current pseudo-cursor
	@Field(0) 
	public int _cury() {
		return this.io.getIntField(this, 0);
	}
	/// current pseudo-cursor
	@Field(0) 
	public WINDOW _cury(int _cury) {
		this.io.setIntField(this, 0, _cury);
		return this;
	}
	@Field(1) 
	public int _curx() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WINDOW _curx(int _curx) {
		this.io.setIntField(this, 1, _curx);
		return this;
	}
	/// max window coordinates
	@Field(2) 
	public int _maxy() {
		return this.io.getIntField(this, 2);
	}
	/// max window coordinates
	@Field(2) 
	public WINDOW _maxy(int _maxy) {
		this.io.setIntField(this, 2, _maxy);
		return this;
	}
	@Field(3) 
	public int _maxx() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public WINDOW _maxx(int _maxx) {
		this.io.setIntField(this, 3, _maxx);
		return this;
	}
	/// origin on screen
	@Field(4) 
	public int _begy() {
		return this.io.getIntField(this, 4);
	}
	/// origin on screen
	@Field(4) 
	public WINDOW _begy(int _begy) {
		this.io.setIntField(this, 4, _begy);
		return this;
	}
	@Field(5) 
	public int _begx() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public WINDOW _begx(int _begx) {
		this.io.setIntField(this, 5, _begx);
		return this;
	}
	/// window properties
	@Field(6) 
	public int _flags() {
		return this.io.getIntField(this, 6);
	}
	/// window properties
	@Field(6) 
	public WINDOW _flags(int _flags) {
		this.io.setIntField(this, 6, _flags);
		return this;
	}
	/**
	 * standard attributes and colors<br>
	 * C type : chtype
	 */
	@org.bridj.ann.CLong 
	@Field(7) 
	public long _attrs() {
		return this.io.getCLongField(this, 7);
	}
	/**
	 * standard attributes and colors<br>
	 * C type : chtype
	 */
	@org.bridj.ann.CLong 
	@Field(7) 
	public WINDOW _attrs(long _attrs) {
		this.io.setCLongField(this, 7, _attrs);
		return this;
	}
	/**
	 * background, normally blank<br>
	 * C type : chtype
	 */
	@org.bridj.ann.CLong 
	@Field(8) 
	public long _bkgd() {
		return this.io.getCLongField(this, 8);
	}
	/**
	 * background, normally blank<br>
	 * C type : chtype
	 */
	@org.bridj.ann.CLong 
	@Field(8) 
	public WINDOW _bkgd(long _bkgd) {
		this.io.setCLongField(this, 8, _bkgd);
		return this;
	}
	/**
	 * causes clear at next refresh<br>
	 * C type : _bool
	 */
	@Field(9) 
	public byte _clear() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * causes clear at next refresh<br>
	 * C type : _bool
	 */
	@Field(9) 
	public WINDOW _clear(byte _clear) {
		this.io.setByteField(this, 9, _clear);
		return this;
	}
	/**
	 * leaves cursor where it is<br>
	 * C type : _bool
	 */
	@Field(10) 
	public byte _leaveit() {
		return this.io.getByteField(this, 10);
	}
	/**
	 * leaves cursor where it is<br>
	 * C type : _bool
	 */
	@Field(10) 
	public WINDOW _leaveit(byte _leaveit) {
		this.io.setByteField(this, 10, _leaveit);
		return this;
	}
	/**
	 * allows window scrolling<br>
	 * C type : _bool
	 */
	@Field(11) 
	public byte _scroll() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * allows window scrolling<br>
	 * C type : _bool
	 */
	@Field(11) 
	public WINDOW _scroll(byte _scroll) {
		this.io.setByteField(this, 11, _scroll);
		return this;
	}
	/**
	 * input character wait flag<br>
	 * C type : _bool
	 */
	@Field(12) 
	public byte _nodelay() {
		return this.io.getByteField(this, 12);
	}
	/**
	 * input character wait flag<br>
	 * C type : _bool
	 */
	@Field(12) 
	public WINDOW _nodelay(byte _nodelay) {
		this.io.setByteField(this, 12, _nodelay);
		return this;
	}
	/**
	 * immediate update flag<br>
	 * C type : _bool
	 */
	@Field(13) 
	public byte _immed() {
		return this.io.getByteField(this, 13);
	}
	/**
	 * immediate update flag<br>
	 * C type : _bool
	 */
	@Field(13) 
	public WINDOW _immed(byte _immed) {
		this.io.setByteField(this, 13, _immed);
		return this;
	}
	/**
	 * synchronise window ancestors<br>
	 * C type : _bool
	 */
	@Field(14) 
	public byte _sync() {
		return this.io.getByteField(this, 14);
	}
	/**
	 * synchronise window ancestors<br>
	 * C type : _bool
	 */
	@Field(14) 
	public WINDOW _sync(byte _sync) {
		this.io.setByteField(this, 14, _sync);
		return this;
	}
	/**
	 * flags keypad key mode active<br>
	 * C type : _bool
	 */
	@Field(15) 
	public byte _use_keypad() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * flags keypad key mode active<br>
	 * C type : _bool
	 */
	@Field(15) 
	public WINDOW _use_keypad(byte _use_keypad) {
		this.io.setByteField(this, 15, _use_keypad);
		return this;
	}
	/**
	 * pointer to line pointer array<br>
	 * C type : chtype**
	 */
	@Field(16) 
	public Pointer<Pointer<org.bridj.CLong > > _y() {
		return this.io.getPointerField(this, 16);
	}
	/**
	 * pointer to line pointer array<br>
	 * C type : chtype**
	 */
	@Field(16) 
	public WINDOW _y(Pointer<Pointer<org.bridj.CLong > > _y) {
		this.io.setPointerField(this, 16, _y);
		return this;
	}
	/**
	 * first changed character in line<br>
	 * C type : int*
	 */
	@Field(17) 
	public Pointer<Integer > _firstch() {
		return this.io.getPointerField(this, 17);
	}
	/**
	 * first changed character in line<br>
	 * C type : int*
	 */
	@Field(17) 
	public WINDOW _firstch(Pointer<Integer > _firstch) {
		this.io.setPointerField(this, 17, _firstch);
		return this;
	}
	/**
	 * last changed character in line<br>
	 * C type : int*
	 */
	@Field(18) 
	public Pointer<Integer > _lastch() {
		return this.io.getPointerField(this, 18);
	}
	/**
	 * last changed character in line<br>
	 * C type : int*
	 */
	@Field(18) 
	public WINDOW _lastch(Pointer<Integer > _lastch) {
		this.io.setPointerField(this, 18, _lastch);
		return this;
	}
	/// top of scrolling region
	@Field(19) 
	public int _tmarg() {
		return this.io.getIntField(this, 19);
	}
	/// top of scrolling region
	@Field(19) 
	public WINDOW _tmarg(int _tmarg) {
		this.io.setIntField(this, 19, _tmarg);
		return this;
	}
	/// bottom of scrolling region
	@Field(20) 
	public int _bmarg() {
		return this.io.getIntField(this, 20);
	}
	/// bottom of scrolling region
	@Field(20) 
	public WINDOW _bmarg(int _bmarg) {
		this.io.setIntField(this, 20, _bmarg);
		return this;
	}
	/// milliseconds of delay for getch()
	@Field(21) 
	public int _delayms() {
		return this.io.getIntField(this, 21);
	}
	/// milliseconds of delay for getch()
	@Field(21) 
	public WINDOW _delayms(int _delayms) {
		this.io.setIntField(this, 21, _delayms);
		return this;
	}
	/// coords relative to parent (0,0)
	@Field(22) 
	public int _parx() {
		return this.io.getIntField(this, 22);
	}
	/// coords relative to parent (0,0)
	@Field(22) 
	public WINDOW _parx(int _parx) {
		this.io.setIntField(this, 22, _parx);
		return this;
	}
	/// coords relative to parent (0,0)
	@Field(23) 
	public int _pary() {
		return this.io.getIntField(this, 23);
	}
	/// coords relative to parent (0,0)
	@Field(23) 
	public WINDOW _pary(int _pary) {
		this.io.setIntField(this, 23, _pary);
		return this;
	}
	/**
	 * subwin's pointer to parent win<br>
	 * C type : _win*
	 */
	@Field(24) 
	public Pointer<WINDOW > _parent() {
		return this.io.getPointerField(this, 24);
	}
	/**
	 * subwin's pointer to parent win<br>
	 * C type : _win*
	 */
	@Field(24) 
	public WINDOW _parent(Pointer<WINDOW > _parent) {
		this.io.setPointerField(this, 24, _parent);
		return this;
	}
	public WINDOW(Pointer pointer) {
		super(pointer);
	}
}
